# -*- coding: utf-8 -*-
"""transpose_2d.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15CmsBskryeQ5VsKfgfpWwTNwiiT5znEb
"""

import numpy as np
array_2d=np.array([[1,2],[3,4]])
print(np.transpose(array_2d))